steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'compute', 
    'ssh', 
    'mahendar_guda@ci-cd-test-instance', 
    '--zone=us-central1-a', 
    '--command', 'sudo /home/mahendar_guda/deploy.sh'
  ]
  id: 'ssh-to-vm'
  serviceAccount: 'cicdpipelinefortestservers@dingoo-backups.iam.gserviceaccount.com'

timeout: '600s'

logsBucket: 'gs://manavbvbucket'

